### ISSUE TITLE
Consider importing the RO-Terms used in workflow_run.yaml instead of defining them inline

### ISSUE THREAD

**Issue by ptsefton** [WEHI-SODA-Hub/proclaim#10]
The YAML file imports schema.org and formal_parameter from elsewere.

The slots defined like this:

```yaml
 tag:
    comments:
    - A tag assigned to a software product, such as a container image
    slot_uri: wfrun:tag
    range: Text
  resourceUsage:
    comments:
    - A resource usage item, such as peak memory
    slot_uri: wfrun:resourceUsage
    range: PropertyValue
  sourceParameter:
    comments:
    - The source (upstream) parameter
    slot_uri: wfrun:sourceParameter
    range: FormalParameter

```

Actually come from the RO-Terms. It would be better if these were imported as well.
