### ISSUE TITLE
YAML files will need something for Dataset with the minimum props for a crate (none in process_run.yaml)

### ISSUE THREAD

**Issue by ptsefton** [WEHI-SODA-Hub/proclaim#9]
This is an issue for all profiles -- do they aim to specify enough to make a useful data package (I think they should) see this issue https://github.com/ResearchObject/workflow-run-crate/issues/88 

I would expect to see something like this with some help-text to encourage users to fill out contextual info like author/creator

```yaml
classes:
  Dataset:
    comments:
    - The entry point to a workflow RO-Crate
    is_a: CreativeWork
    class_uri: wfrun:Dataset
    slots:
    - name
    - description
    - datePublished
    - license
    - mainEntity
    - author
    - publisher
```

**Comment by multimeric** [comment]
You're referring to the root data entity here, correct? 

I suppose the best way to do this in LinkML is define this as a new class, because it doesn't make sense to re-define `Dataset` globally, which needs to be re-used for other directories. So I envisage something like:

```yml
classes:
  ProcessRunDataset:
    comments:
    - The entry point to a workflow RO-Crate
    is_a: CreativeWork
    class_uri: wfrun:Dataset
    slots:
      [...]
    - datePublished
   slot_usage:
     datePublished:
       required: true
```

Then they will need to declare their root data entity as a:
```json
"@type": ["Dataset", "ProcessRunDataset"]
```
